name: Test Elevated PowerShell via Batch

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-elevated-script:
    runs-on: windows-latest # runs as Administrator by default :contentReference[oaicite:2]{index=2}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # :contentReference[oaicite:3]{index=3}

      - name: Show current directory
        shell: cmd
        run: |
          echo Current folder is:
          echo %CD%                                                      # prints GITHUB_WORKSPACE by default :contentReference[oaicite:4]{index=4}

      - name: Confirm presence of run.bat
        shell: cmd
        run: |
          echo Listing repo root:
          dir .

      - name: Display run.bat contents
        shell: cmd
        run: type .\run.bat # simpler relative path :contentReference[oaicite:5]{index=5}

      - name: Execute run.bat
        shell: cmd
        run: call .\run.bat # `call` returns to the workflow on exit :contentReference[oaicite:6]{index=6}

      - name: Verify PS script ran
        shell: pwsh
        run: |
          # Check for the transcript logfile your PS script generates
          $logs = Get-ChildItem -Path $PWD -Filter "setup_*.log"
          if (-not $logs) { Write-Error "No log files found – script may not have run." }
          else { Write-Host "Found transcript:"; $logs.FullName }
